# Generated by Django 5.2.9 on 2025-12-11 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractingPlanning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description of specific contracting needs",
                        verbose_name="Description",
                    ),
                ),
                (
                    "ai_summary",
                    models.TextField(
                        blank=True,
                        help_text="AI-generated summary of the project",
                        null=True,
                        verbose_name="AI Generated Summary",
                    ),
                ),
                (
                    "ai_questions",
                    models.JSONField(
                        blank=True,
                        help_text="Questions generated by AI to clarify requirements",
                        null=True,
                        verbose_name="AI Generated Questions",
                    ),
                ),
                (
                    "user_answers",
                    models.JSONField(
                        blank=True,
                        help_text="User's answers to AI-generated questions",
                        null=True,
                        verbose_name="User Answers",
                    ),
                ),
                (
                    "selected_contractors",
                    models.JSONField(
                        blank=True,
                        help_text="Array of contractor IDs selected for invitation",
                        null=True,
                        verbose_name="Selected Contractors",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Contracting Planning",
                "verbose_name_plural": "Contracting Plannings",
            },
        ),
        migrations.CreateModel(
            name="Contractor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Contractor Name"),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Address"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="City"),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Postal Code"
                    ),
                ),
                (
                    "state",
                    models.CharField(blank=True, max_length=100, verbose_name="State"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Phone"),
                ),
                ("website", models.URLField(blank=True, verbose_name="Website")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "price_range",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Price Range"
                    ),
                ),
                (
                    "service_area",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Service Area"
                    ),
                ),
                (
                    "business_size",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Business Size"
                    ),
                ),
                (
                    "years_in_business",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Years in Business"
                    ),
                ),
                ("services", models.TextField(blank=True, verbose_name="Services")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "specializations",
                    models.TextField(blank=True, verbose_name="Specializations"),
                ),
                (
                    "rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Rating out of 5.0",
                        max_digits=3,
                        null=True,
                        verbose_name="Rating",
                    ),
                ),
                (
                    "reviews_count",
                    models.IntegerField(default=0, verbose_name="Reviews Count"),
                ),
                (
                    "certifications",
                    models.TextField(blank=True, verbose_name="Certifications"),
                ),
                (
                    "kfw_eligible",
                    models.BooleanField(default=False, verbose_name="KfW Eligible"),
                ),
                (
                    "source",
                    models.CharField(blank=True, max_length=100, verbose_name="Source"),
                ),
                (
                    "additional_info",
                    models.TextField(blank=True, verbose_name="Additional Info"),
                ),
                (
                    "project_types",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated list of project types (e.g., 'kitchen,bathroom,plumbing')",
                        max_length=500,
                        verbose_name="Project Types",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contractor",
                "verbose_name_plural": "Contractors",
                "ordering": ["-rating", "name"],
            },
        ),
        migrations.CreateModel(
            name="ContractingPlanningFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Uploaded document or photo",
                        upload_to="contracting_planning/%Y/%m/%d/",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contracting_planning",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="core.contractingplanning",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contracting Planning File",
                "verbose_name_plural": "Contracting Planning Files",
            },
        ),
        migrations.CreateModel(
            name="EmailCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("gmail", "Gmail"), ("outlook", "Outlook")],
                        default="gmail",
                        help_text="Email service provider",
                        max_length=20,
                        verbose_name="Email Provider",
                    ),
                ),
                (
                    "access_token",
                    models.TextField(
                        blank=True,
                        help_text="OAuth access token",
                        null=True,
                        verbose_name="Access Token",
                    ),
                ),
                (
                    "refresh_token",
                    models.TextField(
                        blank=True,
                        help_text="OAuth refresh token",
                        null=True,
                        verbose_name="Refresh Token",
                    ),
                ),
                (
                    "token_expiry",
                    models.DateTimeField(
                        blank=True,
                        help_text="Expiry datetime of the access token",
                        null=True,
                        verbose_name="Token Expiry",
                    ),
                ),
                (
                    "email_address",
                    models.EmailField(
                        blank=True,
                        help_text="Email address associated with OAuth",
                        max_length=254,
                        null=True,
                        verbose_name="Email Address",
                    ),
                ),
                (
                    "scopes",
                    models.JSONField(
                        blank=True,
                        help_text="Granted OAuth scopes",
                        null=True,
                        verbose_name="OAuth Scopes",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_credential",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Credential",
                "verbose_name_plural": "Email Credentials",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Project Name")),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("kitchen", "Kitchen Renovation"),
                            ("bathroom", "Bathroom Renovation"),
                            ("basement", "Basement Renovation"),
                            ("roofing", "Roofing"),
                            ("electrical", "Electrical"),
                            ("plumbing", "Plumbing"),
                            ("hvac", "HVAC"),
                            ("flooring", "Flooring"),
                            ("windows_doors", "Windows/Doors"),
                            ("exterior", "Exterior"),
                            ("general", "General Renovation"),
                        ],
                        default="general",
                        max_length=50,
                        verbose_name="Project Type",
                    ),
                ),
                ("address", models.CharField(max_length=200, verbose_name="Address")),
                ("city", models.CharField(max_length=100, verbose_name="City")),
                (
                    "postal_code",
                    models.CharField(max_length=20, verbose_name="Postal Code"),
                ),
                ("state", models.CharField(max_length=100, verbose_name="State")),
                (
                    "budget",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Budget",
                    ),
                ),
                (
                    "additional_information",
                    models.TextField(
                        blank=True,
                        help_text="Additional information about the project",
                        null=True,
                        verbose_name="Additional Information",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("offer_letter", models.FileField(upload_to="offers/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("submitted", "Submitted"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contractor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.contractor",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.project"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="contractingplanning",
            name="project",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contracting_planning",
                to="core.project",
            ),
        ),
        migrations.CreateModel(
            name="SentEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contractor_email",
                    models.EmailField(
                        help_text="Email address of the contractor",
                        max_length=254,
                        verbose_name="Contractor Email",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Subject line of the email",
                        max_length=500,
                        verbose_name="Email Subject",
                    ),
                ),
                (
                    "body_html",
                    models.TextField(
                        help_text="HTML content of the email body",
                        verbose_name="Email Body HTML",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the email was sent",
                        verbose_name="Sent At",
                    ),
                ),
                (
                    "gmail_message_id",
                    models.CharField(
                        blank=True,
                        help_text="Message ID from Gmail API",
                        max_length=255,
                        null=True,
                        verbose_name="Gmail Message ID",
                    ),
                ),
                (
                    "gmail_thread_id",
                    models.CharField(
                        blank=True,
                        help_text="Thread ID from Gmail API",
                        max_length=255,
                        null=True,
                        verbose_name="Gmail Thread ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="Status of the email sending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if sending failed",
                        null=True,
                        verbose_name="Error Message",
                    ),
                ),
                (
                    "contracting_planning",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_emails",
                        to="core.contractingplanning",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sent Email",
                "verbose_name_plural": "Sent Emails",
                "ordering": ["-sent_at"],
            },
        ),
    ]
