# Generated by Django 5.2.9 on 2025-12-11 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contractor_id",
                    models.IntegerField(
                        help_text="ID of the contractor this conversation is with",
                        verbose_name="Contractor ID",
                    ),
                ),
                (
                    "sender",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("ai", "AI Agent"),
                            ("contractor", "Contractor"),
                        ],
                        help_text="Who sent this message",
                        max_length=20,
                        verbose_name="Sender",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="The text content of the message",
                        verbose_name="Message Content",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the message was sent",
                        verbose_name="Timestamp",
                    ),
                ),
                (
                    "contracting_planning",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="core.contractingplanning",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "ordering": ["timestamp"],
                "indexes": [
                    models.Index(
                        fields=["contracting_planning", "contractor_id", "timestamp"],
                        name="core_messag_contrac_48efcd_idx",
                    )
                ],
            },
        ),
    ]
