# Generated by Django 5.2.9 on 2025-12-11 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractingplanning",
            name="current_step",
            field=models.IntegerField(
                default=1,
                help_text="Current step in the contracting workflow (1-4)",
                verbose_name="Current Step",
            ),
        ),
    ]
