# Generated by Django 5.2.8 on 2026-01-11 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_chatmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_type', models.CharField(choices=[('preference', 'User Preference'), ('fact', 'Extracted Fact'), ('project_detail', 'Project Detail'), ('building_info', 'Building Information'), ('budget', 'Budget Information'), ('material', 'Material Preference'), ('timeline', 'Timeline Information')], default='fact', max_length=30)),
                ('key', models.CharField(help_text="Memory identifier, e.g., 'preferred_tiles', 'building_age'", max_length=100)),
                ('value', models.TextField(help_text='The actual memory content')),
                ('confidence', models.FloatField(default=1.0, help_text='Confidence score 0-1 for extracted memories')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive memories are not used in context')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_session', models.ForeignKey(blank=True, help_text='The session this memory was extracted from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracted_memories', to='core.chatsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Memory',
                'verbose_name_plural': 'User Memories',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'key')},
            },
        ),
    ]
