# Generated by Django 4.2.11 on 2026-02-25 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_renovation_plan'),
        ('core', '0004_usermemory'),
    ]

    operations = [
    ]
