# Generated by Django 5.2.9 on 2025-12-12 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_add_message_action_and_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Uploaded file",
                        upload_to="message_attachments/%Y/%m/%d/",
                    ),
                ),
                (
                    "filename",
                    models.CharField(
                        help_text="Original filename",
                        max_length=255,
                        verbose_name="Filename",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        blank=True,
                        help_text="MIME type of the file",
                        max_length=100,
                        verbose_name="Content Type",
                    ),
                ),
                (
                    "file_size",
                    models.IntegerField(
                        help_text="Size in bytes", verbose_name="File Size"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        help_text="The message this attachment is associated with",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="core.message",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message Attachment",
                "verbose_name_plural": "Message Attachments",
                "ordering": ["uploaded_at"],
            },
        ),
    ]
