# Generated by Django 5.2.9 on 2025-12-12 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_messageattachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messageaction",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("send_email", "Send Email"),
                    ("draft_email", "Draft Email"),
                    ("fetch_email", "Fetch Email"),
                    ("analyze_offer", "Analyze Offer"),
                    ("compare_offers", "Compare Offers"),
                ],
                help_text="Type of action to perform",
                max_length=20,
                verbose_name="Action Type",
            ),
        ),
        migrations.CreateModel(
            name="ContractorOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contractor_id",
                    models.IntegerField(
                        help_text="ID of the contractor who made this offer",
                        verbose_name="Contractor ID",
                    ),
                ),
                (
                    "gmail_message_id",
                    models.CharField(
                        help_text="Link to the email containing this offer",
                        max_length=255,
                        unique=True,
                        verbose_name="Gmail Message ID",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total offer price",
                        max_digits=12,
                        null=True,
                        verbose_name="Total Price",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="EUR",
                        help_text="Currency code (ISO 4217)",
                        max_length=3,
                        verbose_name="Currency",
                    ),
                ),
                (
                    "timeline_start",
                    models.DateField(
                        blank=True,
                        help_text="Proposed project start date",
                        null=True,
                        verbose_name="Timeline Start",
                    ),
                ),
                (
                    "timeline_end",
                    models.DateField(
                        blank=True,
                        help_text="Proposed project end date",
                        null=True,
                        verbose_name="Timeline End",
                    ),
                ),
                (
                    "timeline_duration_days",
                    models.IntegerField(
                        blank=True,
                        help_text="Project duration in days",
                        null=True,
                        verbose_name="Timeline Duration (Days)",
                    ),
                ),
                (
                    "scope_of_work",
                    models.TextField(
                        blank=True,
                        help_text="Description of work to be performed",
                        verbose_name="Scope of Work",
                    ),
                ),
                (
                    "materials_included",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of materials included in the offer",
                        verbose_name="Materials Included",
                    ),
                ),
                (
                    "labor_breakdown",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Cost breakdown by labor type",
                        verbose_name="Labor Breakdown",
                    ),
                ),
                (
                    "payment_terms",
                    models.TextField(
                        blank=True,
                        help_text="Payment terms and conditions",
                        verbose_name="Payment Terms",
                    ),
                ),
                (
                    "payment_schedule",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Payment milestones and amounts",
                        verbose_name="Payment Schedule",
                    ),
                ),
                (
                    "warranty_period",
                    models.CharField(
                        blank=True,
                        help_text="Warranty period (e.g., '2 years')",
                        max_length=100,
                        null=True,
                        verbose_name="Warranty Period",
                    ),
                ),
                (
                    "warranty_details",
                    models.TextField(
                        blank=True,
                        help_text="Detailed warranty information",
                        verbose_name="Warranty Details",
                    ),
                ),
                (
                    "insurance_details",
                    models.TextField(
                        blank=True,
                        help_text="Insurance coverage information",
                        verbose_name="Insurance Details",
                    ),
                ),
                (
                    "special_conditions",
                    models.TextField(
                        blank=True,
                        help_text="Any special conditions or notes",
                        verbose_name="Special Conditions",
                    ),
                ),
                (
                    "offer_date",
                    models.DateField(
                        blank=True,
                        help_text="Date the offer was made",
                        null=True,
                        verbose_name="Offer Date",
                    ),
                ),
                (
                    "valid_until",
                    models.DateField(
                        blank=True,
                        help_text="Date until which the offer is valid",
                        null=True,
                        verbose_name="Valid Until",
                    ),
                ),
                (
                    "extracted_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Full extracted JSON for flexibility",
                        verbose_name="Extracted Data",
                    ),
                ),
                (
                    "pdf_attachment_id",
                    models.CharField(
                        blank=True,
                        help_text="Gmail attachment ID if offer was in PDF",
                        max_length=255,
                        null=True,
                        verbose_name="PDF Attachment ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contracting_planning",
                    models.ForeignKey(
                        help_text="The contracting planning this offer is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="core.contractingplanning",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contractor Offer",
                "verbose_name_plural": "Contractor Offers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OfferAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "analysis_type",
                    models.CharField(
                        choices=[
                            ("single", "Single Offer Analysis"),
                            ("comparison", "Offer Comparison"),
                        ],
                        help_text="Type of analysis performed",
                        max_length=20,
                        verbose_name="Analysis Type",
                    ),
                ),
                (
                    "analysis_report",
                    models.TextField(
                        help_text="Markdown formatted analysis report",
                        verbose_name="Analysis Report",
                    ),
                ),
                (
                    "analysis_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Structured analysis data for programmatic access",
                        verbose_name="Analysis Data",
                    ),
                ),
                (
                    "compared_offer_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of offer IDs compared (if type='comparison')",
                        verbose_name="Compared Offer IDs",
                    ),
                ),
                (
                    "documents_used",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of document IDs used in RAG pipeline",
                        null=True,
                        verbose_name="Documents Used",
                    ),
                ),
                (
                    "embeddings_version",
                    models.CharField(
                        blank=True,
                        help_text="Version of embeddings model used",
                        max_length=50,
                        null=True,
                        verbose_name="Embeddings Version",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "offer",
                    models.ForeignKey(
                        help_text="The primary offer being analyzed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to="core.contractoroffer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Offer Analysis",
                "verbose_name_plural": "Offer Analyses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="contractoroffer",
            index=models.Index(
                fields=["contracting_planning", "contractor_id"],
                name="core_contra_contrac_6a40cd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="contractoroffer",
            index=models.Index(
                fields=["gmail_message_id"], name="core_contra_gmail_m_ebdce4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="offeranalysis",
            index=models.Index(
                fields=["offer", "analysis_type"], name="core_offera_offer_i_1dbcea_idx"
            ),
        ),
    ]
