# Generated by Django 5.2.9 on 2025-12-12 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_messageaction_action_type_contractoroffer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractoroffer",
            name="contractor_id",
            field=models.IntegerField(
                blank=True,
                help_text="ID of the contractor who made this offer",
                null=True,
                verbose_name="Contractor ID",
            ),
        ),
        migrations.AlterField(
            model_name="contractoroffer",
            name="currency",
            field=models.CharField(
                blank=True,
                default="EUR",
                help_text="Currency code (ISO 4217)",
                max_length=3,
                null=True,
                verbose_name="Currency",
            ),
        ),
        migrations.AlterField(
            model_name="contractoroffer",
            name="gmail_message_id",
            field=models.CharField(
                blank=True,
                help_text="Link to the email containing this offer",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Gmail Message ID",
            ),
        ),
        migrations.AlterField(
            model_name="contractoroffer",
            name="insurance_details",
            field=models.TextField(
                blank=True,
                help_text="Insurance coverage information",
                null=True,
                verbose_name="Insurance Details",
            ),
        ),
        migrations.AlterField(
            model_name="contractoroffer",
            name="payment_terms",
            field=models.TextField(
                blank=True,
                help_text="Payment terms and conditions",
                null=True,
                verbose_name="Payment Terms",
            ),
        ),
        migrations.AlterField(
            model_name="contractoroffer",
            name="scope_of_work",
            field=models.TextField(
                blank=True,
                help_text="Description of work to be performed",
                null=True,
                verbose_name="Scope of Work",
            ),
        ),
        migrations.AlterField(
            model_name="contractoroffer",
            name="special_conditions",
            field=models.TextField(
                blank=True,
                help_text="Any special conditions or notes",
                null=True,
                verbose_name="Special Conditions",
            ),
        ),
        migrations.AlterField(
            model_name="contractoroffer",
            name="warranty_details",
            field=models.TextField(
                blank=True,
                help_text="Detailed warranty information",
                null=True,
                verbose_name="Warranty Details",
            ),
        ),
    ]
