# Generated by Django 5.2.9 on 2025-12-12 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_contractoroffer_contractor_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractoroffer",
            name="misc_details",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Additional information not captured in other fields (e.g., project manager, certifications, references)",
                verbose_name="Miscellaneous Details",
            ),
        ),
    ]
