# Generated by Django 5.2.9 on 2025-12-12 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_add_misc_details_to_offer"),
    ]

    operations = [
        migrations.CreateModel(
            name="OfferComparisonSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Optional name for this comparison snapshot",
                        max_length=255,
                        null=True,
                        verbose_name="Snapshot Name",
                    ),
                ),
                (
                    "offer_ids",
                    models.JSONField(
                        default=list,
                        help_text="List of offer IDs included in this comparison",
                        verbose_name="Offer IDs",
                    ),
                ),
                (
                    "comparison_data",
                    models.JSONField(
                        default=dict,
                        help_text="Complete structured comparison data with offers, scoring, AI insights, etc.",
                        verbose_name="Comparison Data",
                    ),
                ),
                (
                    "offer_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of offers in this comparison",
                        verbose_name="Offer Count",
                    ),
                ),
                (
                    "recommended_offer_id",
                    models.IntegerField(
                        blank=True,
                        help_text="The offer ID recommended by AI analysis",
                        null=True,
                        verbose_name="Recommended Offer ID",
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this comparison was generated",
                        verbose_name="Generated At",
                    ),
                ),
                (
                    "is_latest",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this is the most recent comparison for this project",
                        verbose_name="Is Latest",
                    ),
                ),
                (
                    "documents_used",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of document IDs used in RAG pipeline",
                        verbose_name="Documents Used",
                    ),
                ),
                (
                    "contracting_planning",
                    models.ForeignKey(
                        help_text="The contracting planning this comparison is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comparison_snapshots",
                        to="core.contractingplanning",
                    ),
                ),
            ],
            options={
                "verbose_name": "Offer Comparison Snapshot",
                "verbose_name_plural": "Offer Comparison Snapshots",
                "ordering": ["-generated_at"],
                "indexes": [
                    models.Index(
                        fields=["contracting_planning", "is_latest"],
                        name="core_offerc_contrac_87ca9c_idx",
                    ),
                    models.Index(
                        fields=["contracting_planning", "generated_at"],
                        name="core_offerc_contrac_d44513_idx",
                    ),
                ],
            },
        ),
    ]
