# Generated by Django 5.2.9 on 2025-12-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_offercomparisonsnapshot"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offercomparisonsnapshot",
            name="contracting_planning",
        ),
        migrations.AlterModelOptions(
            name="contractoroffer",
            options={
                "ordering": ["-email_received_at", "-created_at"],
                "verbose_name": "Contractor Offer",
                "verbose_name_plural": "Contractor Offers",
            },
        ),
        migrations.AddField(
            model_name="contractoroffer",
            name="email_received_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the offer email was received in Gmail",
                null=True,
                verbose_name="Email Received At",
            ),
        ),
        migrations.AddIndex(
            model_name="contractoroffer",
            index=models.Index(
                fields=["email_received_at"], name="core_contra_email_r_04689e_idx"
            ),
        ),
        migrations.DeleteModel(
            name="OfferComparisonSnapshot",
        ),
    ]
