# Generated by Django 5.2.9 on 2025-12-14 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_add_email_received_at_to_contractor_offer"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessedEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gmail_message_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique Gmail message ID to prevent reprocessing",
                        max_length=255,
                        unique=True,
                        verbose_name="Gmail Message ID",
                    ),
                ),
                (
                    "contractor_id",
                    models.IntegerField(
                        help_text="ID of the contractor who sent the email",
                        verbose_name="Contractor ID",
                    ),
                ),
                (
                    "email_subject",
                    models.CharField(
                        blank=True,
                        help_text="Subject line of the email",
                        max_length=500,
                        verbose_name="Email Subject",
                    ),
                ),
                (
                    "email_received_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the email was received in Gmail",
                        null=True,
                        verbose_name="Email Received At",
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the email was processed by our system",
                        verbose_name="Processed At",
                    ),
                ),
                (
                    "contracting_planning",
                    models.ForeignKey(
                        help_text="The contracting planning this email belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processed_emails",
                        to="core.contractingplanning",
                    ),
                ),
                (
                    "created_message",
                    models.ForeignKey(
                        blank=True,
                        help_text="The system message created for this email",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_processed_email",
                        to="core.message",
                    ),
                ),
                (
                    "created_offer",
                    models.ForeignKey(
                        blank=True,
                        help_text="The offer created from this email (if any)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_processed_email",
                        to="core.contractoroffer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Processed Email",
                "verbose_name_plural": "Processed Emails",
                "ordering": ["-processed_at"],
                "indexes": [
                    models.Index(
                        fields=["contracting_planning", "contractor_id"],
                        name="core_proces_contrac_940533_idx",
                    ),
                    models.Index(
                        fields=["gmail_message_id"],
                        name="core_proces_gmail_m_1249b8_idx",
                    ),
                    models.Index(
                        fields=["processed_at"], name="core_proces_process_86c547_idx"
                    ),
                ],
            },
        ),
    ]
