# Generated by Django 5.2.9 on 2025-12-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_processedemail"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_read",
            field=models.BooleanField(
                default=False,
                help_text="Whether the message has been read by the user",
                verbose_name="Is Read",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="read_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the message was marked as read",
                null=True,
                verbose_name="Read At",
            ),
        ),
    ]
